version: 0.2
env:
  parameter-store:
    REACT_APP_CALENDAR_ID: "/chadedwards/public_calendar_id"
    REACT_APP_GOOGLE_API_KEY: "/chadedwards/google_api_key"
    REACT_APP_GOOGLE_SPREADSHEET_ID: "/chadedwards/google_spreadsheet_id"
    REACT_APP_GOOGLE_SHEET_ID: "/chadedwards/google_sheet_id"
    REACT_APP_AWS_SECRET_ACCESS_KEY: "/chadedwards/aws_secret_access_key"
    REACT_APP_AWS_ACCESS_KEY_ID: "/chadedwards/aws_access_key_id"
    REACT_APP_CHADLIBS_SPREADSHEET_ID: "/chadedwards/chadlibs_spreadsheet_id"
    REACT_APP_CHADLIBS_SHEET_ID: "/chadedwards/chadlibs_sheet_id"
    REACT_APP_GPT_KEY: "/chadedwards/gpt_key"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install --global yarn
      - yarn
      - echo "REACT_APP_CALENDAR_ID=$REACT_APP_CALENDAR_ID" >> .env
      - echo "REACT_APP_GOOGLE_API_KEY=$REACT_APP_GOOGLE_API_KEY" >> .env
      - echo "REACT_APP_GOOGLE_SPREADSHEET_ID=REACT_APP_GOOGLE_SPREADSHEET_ID" >> .env
      - echo "REACT_APP_GOOGLE_SHEET_ID=$REACT_APP_GOOGLE_SHEET_ID" >> .env
      - echo "REACT_APP_AWS_SECRET_ACCESS_KEY=$REACT_APP_AWS_SECRET_ACCESS_KEY" >> .env
      - echo "REACT_APP_AWS_ACCESS_KEY_ID=REACT_APP_AWS_ACCESS_KEY_ID" >> .env
      - echo "REACT_APP_CHADLIBS_SPREADSHEET_ID=REACT_APP_CHADLIBS_SPREADSHEET_ID" >> .env
      - echo "REACT_APP_CHADLIBS_SHEET_ID=REACT_APP_CHADLIBS_SHEET_ID" >> .env
      - echo "REACT_APP_GPT_KEY=REACT_APP_GPT_KEY" >> .env
  build:
    commands:
      - cat .env
      - yarn build
  post_build:
    commands:
      - aws s3 sync build s3://chadedwardsband.com
      - aws cloudfront create-invalidation --paths /index.html --distribution-id E2Z5GH3I4QJ67B
artifacts:
  files:
    - 'build/*'

